configs:
  - id: test-tag-
    type:
      settings:
        schema: builtin:tags.auto-tagging
        scope: environment
    config:
      template: "auto-tag.json"
      name: "tag-changed1"
      parameters:
        webAppName: "WebApp2"
    environmentOverrides:
    - environment: uqq74301
      override:
        name: "tag1 uqq74301"
        parameters:
          content: "Some even better Text!"
    - environment: swi350_prod
      override:
        name: "tag1 swi350"
        parameters:
          webAppName: "App in Swi350!"
